# Generated by Django 5.1.6 on 2025-03-07 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('seat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('seat_type', models.CharField(choices=[('normal', '普通座位'), ('regular', '普通座位'), ('corner', '角落座位'), ('VIP', 'vip座位'), ('toilet', '厕所区域'), ('special', '特殊区域')], max_length=20)),
                ('status', models.CharField(default='available', max_length=10)),
                ('x_pos', models.IntegerField(default=0)),
                ('y_pos', models.IntegerField(default=0)),
                ('has_power', models.BooleanField(default=False)),
                ('near_window', models.BooleanField(default=False)),
                ('distance_to_door', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'seats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='reserved', max_length=10)),
                ('checked_in', models.IntegerField(blank=True, default=0)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LSRS.seats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservations',
                'managed': True,
                'indexes': [models.Index(fields=['seat', 'start_time', 'end_time'], name='reservation_seat_id_905b61_idx'), models.Index(fields=['status', 'end_time'], name='reservation_status_a23f5a_idx')],
            },
        ),
    ]
