# Generated by Django 5.1.5 on 2025-01-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LSRS", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="a",
            fields=[("id", models.AutoField(primary_key=True, serialize=False)),],
        ),
    ]
