# Generated by Django 5.1.6 on 2025-03-08 00:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSRS', '0002_alter_reservations_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='reservation_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
